# Generated by Django 5.0.6 on 2024-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DEV', 'Developer'), ('ORG', 'Organization')], max_length=20),
        ),
    ]
