# Generated by Django 5.0.6 on 2024-07-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DEV', 'Developer'), ('ORG', 'Organizer')], default='DEV', max_length=20),
        ),
    ]
