# Generated by Django 5.0 on 2023-12-24 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='enrolled_users',
            field=models.ManyToManyField(related_name='enrolled_contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
