# Generated by Django 5.0 on 2023-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_question_contest_alter_testcase_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
