# Generated by Django 5.0 on 2023-12-24 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_description_contest_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
