# Generated by Django 5.0 on 2023-12-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_alter_contest_description_alter_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
