# Generated by Django 5.0 on 2023-12-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_submission_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
