# Generated by Django 5.0 on 2023-12-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_contest_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
