# Generated by Django 5.0 on 2024-01-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_alter_contest_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='inputs',
            field=models.TextField(blank=True),
        ),
    ]
