# Generated by Django 5.0 on 2024-01-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_question_code_template_testcase_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lang',
            field=models.CharField(default='python', max_length=15),
            preserve_default=False,
        ),
    ]
