# Generated by Django 5.0 on 2024-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_submission_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
