# Generated by Django 5.0 on 2024-01-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_alter_testcase_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='contest',
        ),
    ]
