# Generated by Django 5.0 on 2024-01-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_remove_submission_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='inputs',
            new_name='input',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='attempt',
        ),
        migrations.AlterField(
            model_name='submission',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
