# Generated by Django 5.0 on 2024-01-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_rename_inputs_testcase_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='success',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
