# Generated by Django 5.0 on 2024-01-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_alter_submission_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C'), ('cpp', 'Cpp'), ('javascript', 'JavaScript')], max_length=15),
        ),
    ]
