# Generated by Django 5.0 on 2024-01-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_alter_submission_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
