# Generated by Django 5.0.6 on 2024-07-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
