# Generated by Django 5.0.6 on 2024-07-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_attemptstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptstatus',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
