# Generated by Django 5.0.6 on 2024-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_attemptstatus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptstatus',
            name='language',
            field=models.CharField(default='python', max_length=15),
            preserve_default=False,
        ),
    ]
